version: '3.8'
services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Un!q@to2023 
    container_name: mssql-container
    networks:
      - devops-network

  webserver:
    build:
      context: .
      dockerfile: webserver.Dockerfile
    container_name: webserver-container
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mssql-server
    networks:
      - devops-network

networks:
  devops-network:
